name: BackForce
main: _64FF00\xSudo\xSudo
version: 1.0.0
api: [1.0.0]
load: STARTUP
author: T
description: Only for GENZITU SERVER
website: 
permissions:
 pp.*:
  children:
   pp.all:
    description: ""
    default: op
   pp.suder:
    description: ""