name: PlayerPrivacy
main: _64FF00\xSudo\xSudo
version: 1.0.1
api: [1.0.0]
load: STARTUP
author: T
description: A few tools contained
website: 
permissions:
 pp.*:
  children:
   pp.all:
    description: ""
    default: op
   pp.suder:
    description: ""